/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestWatchOnly {
    }
    interface TestWatchWithProp {
        "fakeProp": string;
    }
}
declare global {
    interface HTMLTestWatchOnlyElement extends Components.TestWatchOnly, HTMLStencilElement {
    }
    var HTMLTestWatchOnlyElement: {
        prototype: HTMLTestWatchOnlyElement;
        new (): HTMLTestWatchOnlyElement;
    };
    interface HTMLTestWatchWithPropElement extends Components.TestWatchWithProp, HTMLStencilElement {
    }
    var HTMLTestWatchWithPropElement: {
        prototype: HTMLTestWatchWithPropElement;
        new (): HTMLTestWatchWithPropElement;
    };
    interface HTMLElementTagNameMap {
        "test-watch-only": HTMLTestWatchOnlyElement;
        "test-watch-with-prop": HTMLTestWatchWithPropElement;
    }
}
declare namespace LocalJSX {
    interface TestWatchOnly {
    }
    interface TestWatchWithProp {
        "fakeProp"?: string;
    }
    interface IntrinsicElements {
        "test-watch-only": TestWatchOnly;
        "test-watch-with-prop": TestWatchWithProp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-watch-only": LocalJSX.TestWatchOnly & JSXBase.HTMLAttributes<HTMLTestWatchOnlyElement>;
            "test-watch-with-prop": LocalJSX.TestWatchWithProp & JSXBase.HTMLAttributes<HTMLTestWatchWithPropElement>;
        }
    }
}
